# Introduction to numpy

In [3]:
import numpy as np
a = [10, 20, 30, 40]
b = [50, 60, 70,80]
print(a + b)

[10, 20, 30, 40, 50, 60, 70, 80]


In [5]:
a = [20, 30, 40]
b = 3
print(a * b)

[20, 30, 40, 20, 30, 40, 20, 30, 40]


In [6]:
import numpy as np

In [7]:
arr= np.array([10, 20, 30, 40,50])
print(arr)

[10 20 30 40 50]


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [3]:
arr = np.array([1, 3, 5, 7, 9])
print(arr)

[1 3 5 7 9]


In [4]:
import numpy as np

print(np.__version__)


1.24.3


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 0-D Arrays

In [6]:
import numpy as np

arr = np.array(42)

print(arr)


42


# 1-D Arrays

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [8]:
arr = np.array([2, 4, 6, 8, 10])
print(arr)

[ 2  4  6  8 10]


# 2-D Arrays

In [9]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [10]:
arr = np.array([[1, 3, 5], [2, 4, 6]])
print(arr)

[[1 3 5]
 [2 4 6]]


# 3-D Arrays

In [11]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# N-Dim

In [12]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Indexing

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [15]:
arr = np.array([1, 2, 3, 4])

print(arr[2])

3


In [17]:
arr = np.array([1, 2, 3, 4])

print(arr[3])

4


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


In [19]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [20]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])


5th element on 2nd row:  10


In [21]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


# Slicing

In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:7])

[3 4 5 6 7]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


# Datatypes

In [27]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)


int32


In [28]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)


<U6


# Iterating Arrays

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


[1 2 3]
[4 5 6]


# Join

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [4]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


# Splitting

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


# Searching

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


(array([1, 3, 5, 7], dtype=int64),)


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


# Sorting

In [4]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [5]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']
